name: Build
on:
  push:
    tags:
      - "v*"
env:
  PYTHON_VERSION: 3.9

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: build
        run: pyinstaller -F src/tracking_GUI.py -i img/icon.ico --version-file file_version_info.txt

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: tracking_GUI-windows
          path: dist/tracking_GUI.exe

  macOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: |
          python -m pip install -U pip PyInstaller
          python -m pip install -r requirements.txt

      - name: build
        run: pyinstaller -F src/tracking_GUI.py -i img/icon.ico

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: tracking_GUI-macos
          path: dist/tracking_GUI

  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: |
          python -m pip install -U pip PyInstaller
          python -m pip install -r requirements.txt

      - name: build
        run: pyinstaller -F src/tracking_GUI.py -i img/icon.ico

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: tracking_GUI-linux
          path: dist/tracking_GUI

  release:
    needs: [ubuntu-build, macOS-build, windows-build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux
        uses: actions/download-artifact@v1
        with:
          name: tracking_GUI-linux

      - name: Download Mac
        uses: actions/download-artifact@v1
        with:
          name: tracking_GUI-macos

      - name: Download Windows
        uses: actions/download-artifact@v1
        with:
          name: tracking_GUI-windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip
        run: |
          tar -C tracking_GUI-macos -pczvf tracking_GUI-macos.tar.gz tracking_GUI
          tar -C tracking_GUI-linux -pczvf tracking_GUI-linux.tar.gz tracking_GUI
          zip -9 --junk-paths tracking_GUI-windows ./tracking_GUI-windows/tracking_GUI.exe

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

      - name: Append mac Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tracking_GUI-macos.tar.gz
          asset_name: tracking_GUI-macos_${{ env.RELEASE_VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Append linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tracking_GUI-linux.tar.gz
          asset_name: tracking_GUI-linux_${{ env.RELEASE_VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Append win Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tracking_GUI-windows.zip
          asset_name: tracking_GUI-windows_${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
